#pragma once
#include <define.h>
#include <dbt/el/context.h>
#include <dbt/el/emitter.h>
#include <dbt/dbt.h>
#include <aarch64-decode.h>
typedef uint8_t uint8;
typedef uint16_t uint16;
typedef uint32_t uint32;
typedef uint64_t uint64;
typedef int8_t sint8;
typedef int16_t sint16;
typedef int32_t sint32;
typedef int64_t sint64;
namespace captive 
{
  namespace arch 
  {
    namespace aarch64 
    {
      class aarch64_cpu;
      template<bool TRACE>
      class aarch64_jit2 : public captive::arch::jit::DBT 
      {
        public:
        aarch64_jit2();
        ~aarch64_jit2();
        bool translate(const Decode *decode_obj, captive::arch::dbt::el::Emitter& emitter) override;
        private:
        captive::arch::dbt::el::Value *generate_predicate_a64_COND_B_IMM(const aarch64_decode_a64_COND_B_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_abs_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_adc(const aarch64_decode_a64_ADD_SUB_CARRY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_add_ereg(const aarch64_decode_a64_ADD_SUB_EREG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_add_sreg(const aarch64_decode_a64_ADD_SUB_SREG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_add_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_addi(const aarch64_decode_a64_ADD_SUB_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_addp_scalar(const aarch64_decode_a64_SIMD_SCALAR_PW& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_addp_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_addv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_adr(const aarch64_decode_a64_PC_REL& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_and_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_andi(const aarch64_decode_a64_LOGICAL_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_andsr(const aarch64_decode_a64_LOGICAL_SR& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_asrv(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_b(const aarch64_decode_a64_UB_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_barrier(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bcond(const aarch64_decode_a64_COND_B_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bfm(const aarch64_decode_a64_BITFIELD& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bic_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bici(const aarch64_decode_a64_SIMD_MOD_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bicsr(const aarch64_decode_a64_LOGICAL_SR& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bif(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bit(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_br(const aarch64_decode_a64_UB_REG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_bsl(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cbz(const aarch64_decode_a64_CMP_B_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ccmni(const aarch64_decode_a64_COND_CMP_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ccmnr(const aarch64_decode_a64_COND_CMP_REG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ccmpi(const aarch64_decode_a64_COND_CMP_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ccmpr(const aarch64_decode_a64_COND_CMP_REG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_clrex(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cls(const aarch64_decode_a64_DP_1S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_clz(const aarch64_decode_a64_DP_1S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cmeq_reg(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cmeq_zero(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cmge_zero(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cmhi_reg(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cmlt_zero(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cmtst(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_cnt(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_crc32(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_crc32c(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_csel(const aarch64_decode_a64_COND_SEL& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_csinc(const aarch64_decode_a64_COND_SEL& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_csinv(const aarch64_decode_a64_COND_SEL& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_csneg(const aarch64_decode_a64_COND_SEL& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_drps(const aarch64_decode_a64_UB_REG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_dup_elem(const aarch64_decode_a64_SIMD_COPY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_dup_gen(const aarch64_decode_a64_SIMD_COPY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_eor_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_eori(const aarch64_decode_a64_LOGICAL_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_eorsr(const aarch64_decode_a64_LOGICAL_SR& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_eret(const aarch64_decode_a64_UB_REG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_exgen(const aarch64_decode_a64_EX_GEN& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ext(const aarch64_decode_a64_SIMD_EXTRACT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_extr(const aarch64_decode_a64_EXTRACT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fabd(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fabs(const aarch64_decode_a64_FP_DP_1& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fadd(const aarch64_decode_a64_FP_DP_2& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fccmpe(const aarch64_decode_a64_FP_CCMP& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcmgt_zero(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcmpe(const aarch64_decode_a64_FP_CMP& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcsel(const aarch64_decode_a64_FP_CSEL& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcvt(const aarch64_decode_a64_FP_DP_1& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcvtas_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcvti(const aarch64_decode_a64_CVT_FP_I& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcvtz(const aarch64_decode_a64_CVT_FP_I& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcvtz_fxp(const aarch64_decode_a64_CVT_FP_FXP& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fcvtzs_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fdiv(const aarch64_decode_a64_FP_DP_2& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fdiv_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fm(const aarch64_decode_a64_FP_DP_3& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmaxnmv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmaxv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fminnmv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fminv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmla_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmov(const aarch64_decode_a64_FP_DP_1& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmov_gen(const aarch64_decode_a64_CVT_FP_I& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmov_simd(const aarch64_decode_a64_SIMD_MOD_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmovi(const aarch64_decode_a64_FP_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmul(const aarch64_decode_a64_FP_DP_2& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fmul_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fneg(const aarch64_decode_a64_FP_DP_1& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fnm(const aarch64_decode_a64_FP_DP_3& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fnmul(const aarch64_decode_a64_FP_DP_2& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_frintx(const aarch64_decode_a64_FP_DP_1& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fsqrt(const aarch64_decode_a64_FP_DP_1& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fsub(const aarch64_decode_a64_FP_DP_2& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_fsub_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_hint(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ins_elem(const aarch64_decode_a64_SIMD_COPY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ins_gen(const aarch64_decode_a64_SIMD_COPY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld1(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld1pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld1r(const aarch64_decode_a64_SIMD_LS_SINGLE& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld1s(const aarch64_decode_a64_SIMD_LS_SINGLE& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld2(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld2pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld3(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld3pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld4(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ld4pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldar(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldarb(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldarh(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldaxp(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldaxr(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldaxrb(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldaxrh(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldnp(const aarch64_decode_a64_LS_NO_ALLOC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldp(const aarch64_decode_a64_LS_REG_PAIR_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldp_simd(const aarch64_decode_a64_LS_REG_PAIR_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldpi(const aarch64_decode_a64_LS_REG_PAIR_IDX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldpi_simd(const aarch64_decode_a64_LS_REG_PAIR_IDX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldpsw(const aarch64_decode_a64_LS_REG_PAIR_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldpswi(const aarch64_decode_a64_LS_REG_PAIR_IDX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldr(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldr_lit(const aarch64_decode_a64_LOAD_REG_LIT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldr_lit_simd(const aarch64_decode_a64_LOAD_REG_LIT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldr_reg(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldr_reg_simd(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrb(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrb_reg(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrbi(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrh(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrh_reg(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrhi(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldri(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrsw(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrsw_lit(const aarch64_decode_a64_LOAD_REG_LIT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldrswi(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldtr(const aarch64_decode_a64_LS_REG_UNPRIV& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldtrb(const aarch64_decode_a64_LS_REG_UNPRIV& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldtrh(const aarch64_decode_a64_LS_REG_UNPRIV& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldtrsw(const aarch64_decode_a64_LS_REG_UNPRIV& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldur(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldurb(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldurh(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldursw(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldxp(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldxr(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldxrb(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ldxrh(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_lslv(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_lsrv(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_madd(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_mla_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_mov(const aarch64_decode_a64_LOGICAL_SR& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_movi(const aarch64_decode_a64_SIMD_MOD_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_movk(const aarch64_decode_a64_MOVE_WIDE_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_movn(const aarch64_decode_a64_MOVE_WIDE_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_movz(const aarch64_decode_a64_MOVE_WIDE_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_mrs(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_msr_imm(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_msr_reg(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_msr_sctlr(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_msub(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_mul_idx_vector(const aarch64_decode_a64_SIMD_VECTOR_IDX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_mul_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_mvni(const aarch64_decode_a64_SIMD_MOD_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_neg_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_not_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_orn_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_orr_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_orri(const aarch64_decode_a64_LOGICAL_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_orrsr(const aarch64_decode_a64_LOGICAL_SR& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_pmull(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_prfm(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_prfm_lit(const aarch64_decode_a64_LOAD_REG_LIT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_prfm_reg(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_prfmi(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_prfum(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_rbit(const aarch64_decode_a64_DP_1S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ret(const aarch64_decode_a64_UB_REG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_rev(const aarch64_decode_a64_DP_1S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_rev16(const aarch64_decode_a64_DP_1S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_rev32(const aarch64_decode_a64_DP_1S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_rev32_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_rev64_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_rorv(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_saddl(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_saddlv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_saddw(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sbc(const aarch64_decode_a64_ADD_SUB_CARRY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sbfm(const aarch64_decode_a64_BITFIELD& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_scvtf(const aarch64_decode_a64_CVT_FP_I& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_scvtf_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sdiv(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_shl_simd(const aarch64_decode_a64_SIMD_SHIFT_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_shll(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smaddl(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smax(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smaxv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smin(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sminv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smov(const aarch64_decode_a64_SIMD_COPY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smsubl(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smulh(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_smull(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sshl(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sshll(const aarch64_decode_a64_SIMD_SHIFT_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sshr(const aarch64_decode_a64_SIMD_SHIFT_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ssubl(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ssubw(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st1(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st1pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st1s(const aarch64_decode_a64_SIMD_LS_SINGLE& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st1spi(const aarch64_decode_a64_SIMD_LS_SINGLE_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st2(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st2pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st3(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st3pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st4(const aarch64_decode_a64_SIMD_LS_MULT& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_st4pi(const aarch64_decode_a64_SIMD_LS_MULT_PI& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stlr(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stlrb(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stlrh(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stlxp(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stlxr(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stlxrb(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stlxrh(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stnp(const aarch64_decode_a64_LS_NO_ALLOC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stp(const aarch64_decode_a64_LS_REG_PAIR_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stp_simd(const aarch64_decode_a64_LS_REG_PAIR_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stpi(const aarch64_decode_a64_LS_REG_PAIR_IDX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stpi_simd(const aarch64_decode_a64_LS_REG_PAIR_IDX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_str(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_str_reg(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_str_reg_simd(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_strb(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_strb_reg(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_strbi(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_strh(const aarch64_decode_a64_LS_REG_IMM_POST& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_strh_reg(const aarch64_decode_a64_LS_REG_REG_OFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_strhi(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stri(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sttr(const aarch64_decode_a64_LS_REG_UNPRIV& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sttrb(const aarch64_decode_a64_LS_REG_UNPRIV& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sttrh(const aarch64_decode_a64_LS_REG_UNPRIV& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stur(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sturb(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sturh(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stxp(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stxr(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stxrb(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_stxrh(const aarch64_decode_a64_LS_EX& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sub_ereg(const aarch64_decode_a64_ADD_SUB_EREG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sub_sreg(const aarch64_decode_a64_ADD_SUB_SREG& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sub_vector(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_subi(const aarch64_decode_a64_ADD_SUB_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_sys(const aarch64_decode_a64_SYSTEM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_tbl(const aarch64_decode_a64_SIMD_TABLE_LOOKUP& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_tbx(const aarch64_decode_a64_SIMD_TABLE_LOOKUP& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_tbz(const aarch64_decode_a64_TEST_B_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uadalp(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uaddl(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uaddlp(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uaddlv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uaddw(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ubfm(const aarch64_decode_a64_BITFIELD& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ucvtf(const aarch64_decode_a64_CVT_FP_I& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ucvtf_simd(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_udiv(const aarch64_decode_a64_DP_2S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_umaddl(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_umaxv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uminv(const aarch64_decode_a64_SIMD_ACROSS_LANES& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_umov(const aarch64_decode_a64_SIMD_COPY& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_umsubl(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_umulh(const aarch64_decode_a64_DP_3S& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_umull(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ushl(const aarch64_decode_a64_SIMD_THREE_SAME& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ushll(const aarch64_decode_a64_SIMD_SHIFT_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_ushr(const aarch64_decode_a64_SIMD_SHIFT_IMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_usubl(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_usubw(const aarch64_decode_a64_SIMD_THREE_DIFF& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uzp1(const aarch64_decode_a64_SIMD_PERMUTE& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_uzp2(const aarch64_decode_a64_SIMD_PERMUTE& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_vldr(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_vldur(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_vstr(const aarch64_decode_a64_LS_REG_UIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_vstur(const aarch64_decode_a64_LS_REG_USIMM& insn, captive::arch::dbt::el::Emitter& emitter);
        bool translate_a64_xtn(const aarch64_decode_a64_SIMD_TWO_REG_MISC& insn, captive::arch::dbt::el::Emitter& emitter);
      }
      ;
    }
  }
}
