/* SPDX-License-Identifier: MIT */
#pragma once

// System Config
//#define CONFIG_USER_MODE
#define LAPIC_TIMER_FREQUENCY		100
//#define CONFIG_PROFILE
#define QUIET

// Compilation Config
#define CONFIG_BLOCK_CHAINING
#define CONFIG_BLOCK_DISPATCHING
#define CONFIG_TRACE_BASED

// DBT Config
//#define CONFIG_FANCY_VECTOR
//#define CONFIG_FORCED_ICACHE_INVALIDATIONS

// Profiling Config
//#define CONFIG_TIME_EXECUTION
//#define CONFIG_TIME_COMPILATION
//#define CONFIG_COMPILATION_DRILLDOWN
//#define CONFIG_COUNT_INSTRUCTIONS
//#define CONFIG_AGGREGATE_BLOCK_EXECUTION
//#define CONFIG_PROFILE_COMPILATION
//#define CONFIG_PROFILE_HOST_PER_GUEST

// Debugging
#define CONFIG_PRINT_UNKNOWN_INSTRUCTIONS

// MMU Config
#define MMU_STRATEGY_GUEST	0
#define MMU_STRATEGY_SOFT	1
#define MMU_STRATEGY_TVAS	2
#define MMU_STRATEGY_PGTSW	3
#define MMU_STRATEGY_MPK	4
#define MMU_STRATEGY_STAG	5

#define CONFIG_MMU_STRATEGY			MMU_STRATEGY_SOFT
